# Generated by Django 3.0.2 on 2020-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
