# Generated by Django 3.0.2 on 2020-09-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
