# Generated by Django 3.0.2 on 2020-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0003_remove_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='page_no',
            field=models.IntegerField(default=1),
        ),
    ]
