# Generated by Django 3.0.2 on 2020-09-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0004_auto_20200914_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
    ]
