# Generated by Django 3.0.2 on 2020-09-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0005_auto_20200914_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail_text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_text',
        ),
    ]
