# Generated by Django 3.0.2 on 2020-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0006_auto_20200914_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='App_Shop.Author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
