# Generated by Django 3.0.2 on 2020-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0007_auto_20200914_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
